# Site settings
title: Treviso JS
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Benvenuti in Treviso JS! I nostri incontri del Mercoledì sera hanno lo scopo di scoprire JS con un approccio "hands-on".
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username:
github_username:  trevisojs

# Build settings
markdown: kramdown
